### ISSUE TITLE
add app error

### ISSUE THREAD

**Issue by andy27182** [cfs-tools/cfs-basecamp#55]
Hi,
When I try to add the app in the gui, I use the manual increase method, and an error occurs in the terminal.

```
Traceback (most recent call last):
  File "basecamp.py", line 2117, in <module>
    execute = app.execute()
  File "basecamp.py", line 1653, in execute
    manage_cfs.execute(self.event.split(' ')[0])
  File "basecamp.py", line 763, in execute
    self.add_usr_app_gui(usr_app_list)
  File "basecamp.py", line 646, in add_usr_app_gui
    self.copy_app_tables(auto_copy=False)  # Copy table files from app dir to cFS '_defs' file
  File "basecamp.py", line 790, in copy_app_tables
    table_list = self.get_app_table_list()
  File "basecamp.py", line 773, in get_app_table_list
    app_cmake_files = self.usr_app_spec.get_targets_cmake_files()
AttributeError: 'NoneType' object has no attribute 'get_targets_cmake_files'
```

I try to increase the assignment of `usr_app_spec` on the` manual button event`, and the function can be normal.
```
            elif self.event == '-1X_MAN-':
                self.selected_app = self.values['-USR_APP-']
                self.usr_app_spec = self.manage_usr_apps.get_app_spec(self.selected_app)
```

**Comment by AndrewFrank-zxy** [comment]
Hi
I'm trying to add a new `app (pl_mgr)` via `gui`, and I'm getting an error during `build the cfs`, `PL_SIM_LIB/Power` can't be resolved . I'm looking for the cause of the problem, but I'm not very familiar with the `lua` language
```
/cfs-basecamp/usr/apps/pl_mgr/eds/pl_mgr.xml:56:error: attribute 'type' could not be resolved - PL_SIM_LIB/Power
Processing Error - stack traceback:
	...ramework/tools/eds/tool/scripts/10-seds_resolve_refs.lua:468: in main chunk
Aborted (core dumped)
make[4]: *** [CMakeFiles/edstool-execute.dir/build.make:97: edstool-complete.stamp] Error 134
make[3]: *** [CMakeFiles/Makefile2:550: CMakeFiles/edstool-execute.dir/all] Error 2
make[2]: *** [CMakeFiles/Makefile2:476: CMakeFiles/mission-install.dir/rule] Error 2
make[1]: *** [Makefile:175: mission-install] Error 2
make: *** [Makefile:135: topicids] Error 2
```

**Comment by dmccomas** [comment]
I need more information for the first issue. Can you describe the steps you are trying to do so I can replicate the issue. For example, 
1. I downloaded pl_mgr from github
2. Which specific steps in the "Add User App" passed and on which step it failed 

For the second issue it looks like you didn't add pl_sim_lib first.  Automated dependency checks will be added, see issue #12.  An app's spec file. e.g. pl_mgr.json, contains a "requires" entry that specifies the app's dependencies.
