### ISSUE TITLE
 which Raspberry Pi boards suitable for use with Basecamp

### ISSUE THREAD

**Issue by 1763545734** [cfs-tools/cfs-basecamp#88]
which Raspberry Pi boards suitable for use with Basecamp

**Comment by open-stemware** [comment]
I have used Basecamp on RPI 3B,3B+, 4B, and 5. Note if you are using the most recent RPI OS called Bookworm then you may have to use Python's virtual environment. I heard of pip package installation issues if you don't.

PI_IOLIB is designed for RPIs 4B and earlier and you select your model in the config.h file. PI_IOLIB is someone else's library that I wrapped to work as a cFS library. It serves as a good example for C interfacing in the GPIO_DEMO app but I have not used many of its features.

Many users do not want to write C interfaces, so I am working on new libs/apps that will allow simple python scripts to interface with hardware and communicate with a basecamp app using JSON messages.  Initial versions of these libs/apps will be released in July.

**Comment by 1763545734** [comment]
Thank you  for your answer！If I want to port cFS to the TI hardware processor platform, what kind of learning and work would be required? Could you provide some suggestions？

**Comment by open-stemware** [comment]
This issue is being closed and has been moved to Discussion #89

**Comment by open-stemware** [comment]
cFS porting documentation has been lacking. I've been retired for almost 5
years so there may be material that I'm not aware of.

I've cc'd Alan Cudmore who specializes in cFS porting and he may have some
resources.

- Dave

**Comment by 1763545734** [comment]
Thank you for informing me about the cFS porting documentation status. I appreciate the update and your effort in reaching out.
