### ISSUE TITLE
Add support to create projects

### ISSUE THREAD

**Issue by open-stemware** [cfs-tools/cfs-basecamp#98]
Currently users are responsible for knowing which libs/apps to download and add to a cFS target. This issue proposes that projects should be defined that contain all of the information for automatically creating an educational project using the Basecamp apps.  This first enhancement should automate the current manual target process.  The project libs/apps will simply augment the user's current cFS target.  A future enhancement could be to have a project management feature so multiple cFS project targets are maintained.   A follow-on issue will be written if needed.

**Comment by dmccomas** [comment]
Many projects require Basecamp and/or app table configurations. The issue is being closed taking the approach to inform the user about the configuration requirements, and it is up to them to implement them. Issue #100 has been opened to look into automating this process.
